### ISSUE TITLE
Custom fling velocity adjusment

### ISSUE THREAD

**Issue by daftar-ebrahimi** [ShawnLin013/NumberPicker#106]
There is a final SELECTOR_MAX_FLING_VELOCITY_ADJUSTMENT = 8 in the code which we want to be able to change it with a public setter method.

**Comment by chrisdepas** [comment]
Hey @ShawnLin013 , thanks for implementing this! Android doesn't seem to recognize the attribute, has this been released yet?

**Comment by ShawnLin013** [comment]
Hi @daftar-ebrahimi and @chrisdepas,
This feature is supported from v2.4.8. 
```java
setMaxFlingVelocityCoefficient(int coefficient)
```
or
```xml
app:np_maxFlingVelocityCoefficient="coefficient"
```
