### ISSUE TITLE
Change gravity of text

### ISSUE THREAD

**Issue by arthtilva** [ShawnLin013/NumberPicker#114]
We are not able to change the gravity of the text, right now its centred. If we can update that it would be great relief and usable. (if not possible for attributes its fine, but i have imported code and used java files in the code so i can update that also.)

**Comment by ShawnLin013** [comment]
Hi @arthtilva,

Thank you for your suggestion. 🙏 

This feature is supported at v2.4.7. Please try the following code snippet.

```java
int align = NumberPicker.CENTER; // NumberPicker.LEFT, NumberPicker.CENTER, NumberPicker.RIGHT
numberPicker.setSelectedTextAlign(align);
numberPicker.setTextAlign(align);
```

or

```xml

app:np_selectedTextAlign="selectedTextAlignCenter" // selectedTextAlignLeft, selectedTextAlignCenter, selectedTextAlignRight
app:np_textAlign="textAlignCenter" // textAlignLeft, textAlignCenter, textAlignRight
```
