### ISSUE TITLE
How to apple strikethrough style to items?

### ISSUE THREAD

**Issue by dev-alysenko** [ShawnLin013/NumberPicker#115]
Hi @ShawnLin013,
is there a possibility to add the strikethrough style to text of displayed items?

**Comment by ShawnLin013** [comment]
Hi @dev-alysenko,

Thank you for your suggestion. 🙏 

This feature is supported at v2.4.7. Please try the following code snippet.

```java
numberPicker.setSelectedTextStrikeThru(true);
numberPicker.setTextStrikeThru(true);
```

or

```xml
app:np_selectedTextStrikeThru="true"
app:np_textStrikeThru="true"
```
