### ISSUE TITLE
No disable feature?

### ISSUE THREAD

**Issue by YamadaKaito** [ShawnLin013/NumberPicker#14]
No enable/disable feature yet, for disabling the spin when waiting for submitting data?
I was able to disable the layout using ViewGroup instances and disabling the children, but NumberPicker still can be spin but feels like buggy, constantly spinning...
Can it be fixed?
Thank You..

**Comment by ShawnLin013** [comment]
@YamadaKaito 
Try this `numberPicker.setEnabled(false);`
It should be working.  :sunglasses:
