### ISSUE TITLE
horizontal mode displayedValues cycle problem

### ISSUE THREAD

**Issue by songmao123** [ShawnLin013/NumberPicker#141]
If we set the NumberPicker string array values, can we set the values cycle mode？

**Comment by ShawnLin013** [comment]
Hi @songmao123, 
Have you tried using `numberPicker.setWrapSelectorWheel(true)`?

**Comment by songmao123** [comment]
I have tried. but it's useless.  The NumberPicker view set max min number, it's cycleable, but if I set the customize strings, it cannot.

**Comment by ShawnLin013** [comment]
Please try the following code snippet

```java
String[] data = {"A", "B", "C", "D", "E", "F", "G", "H", "I"};
numberPicker.setMinValue(1);
numberPicker.setMaxValue(data.length);
numberPicker.setDisplayedValues(data);
numberPicker.setWrapSelectorWheel(true);
```

**Comment by songmao123** [comment]
Yes, it's OK! It's my fault. Thank you very much.

**Comment by songmao123** [comment]
Another question. When in the horizontal mode, Can we set the item display width(or make the item width wrap the content, because when the data string's length a litter greater, the items overlapping ).
