### ISSUE TITLE
setOnValueChangedListener invode when the NumberPicker is scrolling

### ISSUE THREAD

**Issue by songmao123** [ShawnLin013/NumberPicker#146]
`setOnValueChangedListener`'s `onValueChange` method invode when the `NumberPicker` is scrolling, so the method will invoke many times.  Is there any method toggle the `onValueChange` method when the numberpicker in idle state.

**Comment by larten** [comment]
You have to use NumberPicker.OnScrollListener:

```java
numberPicker.setOnScrollListener(new NumberPicker.OnScrollListener() {
            @Override
            public void onScrollStateChange(NumberPicker view, int scrollState) {
                if(scrollState == SCROLL_STATE_IDLE) {
                    Log.i(TAG, String.format(Locale.US, "newVal: %d", view.getValue()));
                }
            }
        });
```

**Comment by alizarei95** [comment]
same problem here , and above comment not helped me , please fix it in next release

**Comment by ShawnLin013** [comment]
The above code snippet is working correctly.
@larten Thank you for your assistance.
