### ISSUE TITLE
I can't get the right value

### ISSUE THREAD

**Issue by bioslack** [ShawnLin013/NumberPicker#149]
I've wrote a code to get the NP's current value to put it in a TextView when a button is pressed. But, instead of getting the "x" value, I get "x+1". For example, when I select on NP 1, I get 2 on the TextView. Here is the code:

`var v1 = np_1.value`
`btn_add.setOncClickListener{`
&nbsp;&nbsp;&nbsp;&nbsp;`textview.text = "$v1"`
`}`

**Comment by ShawnLin013** [comment]
Have you tried installing the sample App?
