### ISSUE TITLE
Fading edges not working.

### ISSUE THREAD

**Issue by liveaffiliates** [ShawnLin013/NumberPicker#15]
Hi I have been not been able to get the fading edges to work. I have tried both in xml and in code.

```
android:fadingEdgeLength="10dp"
android:fadingEdge="horizontal"
android:fadeScrollbars="true"


snoozeDurationPicker.setHorizontalFadingEdgeEnabled(true);
```

Thanks

**Comment by ShawnLin013** [comment]
Dear @liveaffiliates,
The fading edges is enabled by default.
- use `setHorizontalFadingEdgeEnabled(true)` in horizontal orientation.
- use `setVerticalFadingEdgeEnabled(true)` in vertical orientation.

**Comment by liveaffiliates** [comment]
Hi thanks for your response. Like I said in the issue. I tried that and it is now working.

**Comment by liveaffiliates** [comment]
Actually just checked on an emulated Nexus 10 with api 17 and it is working. It is not working on Samsung Galaxy tab 2 Model GT-P5110 android 4.2.2. Why I have no Idea?
