### ISSUE TITLE
How to set number 0 =00, 1= 01

### ISSUE THREAD

**Issue by vunhiem96** [ShawnLin013/NumberPicker#152]
How to set number 0 =00, 1= 01

**Comment by ShawnLin013** [comment]
Hi @vunhiem96,

You can use the following example code
`numberPicker.setFormatter(R.string.number_picker_formatter);` 
or 
` numberPicker.setFormatter(getString(R.string.number_picker_formatter));`

with your string resource, like
`<string name="number_picker_formatter">%02d</string>`

**Comment by ShawnLin013** [comment]
> How to set number 0 =00, 1= 01

Hi @vunhiem96,

You can use the following example code
numberPicker.setFormatter(R.string.number_picker_formatter);
or
numberPicker.setFormatter(getString(R.string.number_picker_formatter));

with your string resource, like
<string name="number_picker_formatter">%02d</string>

**Comment by vunhiem96** [comment]
ok thanks you
