### ISSUE TITLE
np_lineSpacingMultiplier not working

### ISSUE THREAD

**Issue by jnorkus** [ShawnLin013/NumberPicker#155]
Setting this property doesn't seem to do anything at all. I am trying to get the selected line to take less space as the dividers are overlapping the other lines. Not sure if this is the right property for it either.

![Screenshot_20191204-111702](https://user-images.githubusercontent.com/5137138/70129611-bddd1480-1687-11ea-8cf1-0d9170b56120.png)

**Comment by hulan0523** [comment]
get the same problem too.

**Comment by vw2k3** [comment]
Get the same issue too.

**Comment by vw2k3** [comment]
@ShawnLin013 Please help to solve this issue🙏

**Comment by ShawnLin013** [comment]
@jnorkus @hulan0523 @vw2k3 Have you tried using `np_dividerDistance`?

**Comment by ShawnLin013** [comment]
Or use the `np_itemSpacing` from v2.4.12.
Close this inactive issue for now. Please reopen this issue if are still encountering problems.
