### ISSUE TITLE
number formatting in v2.4.8

### ISSUE THREAD

**Issue by alizarei95** [ShawnLin013/NumberPicker#160]
Hi , when i set 4 digits number to NumberPicker it formats value by separating numbers like currency. I don't have this problem with v2.4.6.
any idea?

**Comment by ShawnLin013** [comment]
@alizarei95 Could you provide your code snippet?

**Comment by ShawnLin013** [comment]
> Hi , when i set 4 digits number to NumberPicker it formats value by separating numbers like currency. I don't have this problem with v2.4.6.
> any idea?

@alizarei95 Could you provide your code snippet?

**Comment by alizarei95** [comment]
// setup year number pickers
        npYear.setTypeface(ResourcesCompat.getFont(getContext(), R.font.iran_yekan_fa_num_bold));
        npYear.setMinValue(1300);
        npYear.setMaxValue(1398);
        npYear.setOnValueChangedListener(onValueChangeListener);

![Screenshot_20200226-155409](https://user-images.githubusercontent.com/4469948/75344866-c2911d80-58b0-11ea-8222-188896c2a04e.png)

**Comment by ShawnLin013** [comment]
It's working correctly in v2.4.8.  Have you tried using the latest version v2.4.9?

**Comment by alizarei95** [comment]
Tested v2.4.9 and also have this problem. I don't have this problem in v2.4.6

**Comment by ShawnLin013** [comment]
Have you tried testing on example project?
I tested the above code snippet that you provided and it's working correctly.

**Comment by alizarei95** [comment]
do you set custom typeface?

**Comment by ShawnLin013** [comment]
This issue has been fixed at v2.4.10.
