### ISSUE TITLE
How to get the selected value?

### ISSUE THREAD

**Issue by khurana3192** [ShawnLin013/NumberPicker#17]
What method returns the selected number value?

**Comment by ShawnLin013** [comment]
You can call `numberpicker.getValue()` to get the current value of the picker.
Or implement NumberPicker.OnValueChangeListener() to the picker.
```
numberPicker.setOnValueChangedListener(new NumberPicker.OnValueChangeListener() {
    @Override
    public void onValueChange(NumberPicker picker, int oldVal, int newVal) {
    
    }
});
```

**Comment by khurana3192** [comment]
Thanks for your prompt reply.

I wish I would have made more efforts before asking this

**Comment by ShawnLin013** [comment]
Thank you! ❤️ 
You are welcome!
