### ISSUE TITLE
Scrolling bug with wrapSelectorWheel=false introduced in v2.4.10

### ISSUE THREAD

**Issue by mateuspiresl** [ShawnLin013/NumberPicker#173]
When scrolling from the first or last element, with `wrapSelectorWheel` set to `false`, the scroller automatically moves to the current element. That means it doesn't let you move out from the first and the last element.

**Comment by mateuspiresl** [comment]
Noticed it allows only when the movement is fast enough.

**Comment by balazsbanyai** [comment]
https://github.com/ShawnLin013/NumberPicker/pull/176 fixes this issue

**Comment by ShawnLin013** [comment]
This issue has been fixed at v2.4.11. @mateuspiresl
