### ISSUE TITLE
Scrolling is 'tripping' when at top or bottom when no-wrap and itemCount is >= 5 issue #38

### ISSUE THREAD

**Issue by crackTheCode** [ShawnLin013/NumberPicker#175]
Issue #38 appears on my app

I am using OnePlus 6 android 10 with v2.4.10 of the NumberPicker

**Comment by balazsbanyai** [comment]
https://github.com/ShawnLin013/NumberPicker/pull/176 fixes this issue

**Comment by ShawnLin013** [comment]
This issue has been fixed at v2.4.11. @crackTheCode
