### ISSUE TITLE
The library is failing to build the app saying manifest merger failed

### ISSUE THREAD

**Issue by chaitanyasarary4** [ShawnLin013/NumberPicker#178]
I am getting this issue.

Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.1.0] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:16:5-113:19 to override.

Please help me resolve. Thanks..

**Comment by ShawnLin013** [comment]
@chaitanyasarary4 You need to migrate your project to AndroidX or use the older version 2.4.6

**Comment by chaitanyasarary4** [comment]
> @chaitanyasarary4 You need to migrate your project to AndroidX or use the older version 2.4.6

Thank you so much for the resolution. I have upgraded to AndroidX and now your library is working like charm.
