### ISSUE TITLE
Posibility to change value with animation

### ISSUE THREAD

**Issue by FirstSpectr** [ShawnLin013/NumberPicker#189]
I added arrow buttons to rule the picker and when I use setValue it's changing without animation. Would be great if we could reproduce the click behavior of left/right side of picker.
![image](https://user-images.githubusercontent.com/24965350/104967282-096d9180-59f4-11eb-87bd-0cc8e1b0bffe.png)

Temp solution:
```    
private fun changeValueByOne(increment: Boolean) {
        try {
            val type = Boolean::class.javaPrimitiveType
            val method = binding.numberPicker::class.java.getDeclaredMethod("changeValueByOne", type)
            method.isAccessible = true
            method.invoke(binding.numberPicker, increment)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
```

**Comment by ShawnLin013** [comment]
Have you tried using `smoothScrollToPosition`? @FirstSpectr

**Comment by FirstSpectr** [comment]
> Have you tried using `smoothScrollToPosition`? @FirstSpectr

Thanks, this is much better than using reflection. I thought that the "position" parameter was the index of the element, but in fact it is the value. So I just did this:
```
        binding.ivArrowLeft.setOnClickListener {
            binding.npAgePicker.smoothScrollToPosition(binding.npAgePicker.value - 1)
        }

        binding.ivArrowRight.setOnClickListener {
            binding.npAgePicker.smoothScrollToPosition(binding.npAgePicker.value + 1)
        }
```
Thanks for the answer!
