### ISSUE TITLE
Migrate Artifacts to Another Repository

### ISSUE THREAD

**Issue by commonsguy** [ShawnLin013/NumberPicker#190]
This library is being published to JCenter. [JCenter is being taken down on May 1 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

Ideally, this library would migrate to publish its artifacts on Maven Central or some other artifact repository.

Thanks for considering this!

**Comment by ShawnLin013** [comment]
Successfully migrated to Maven Central Repository. Thanks!
Don't forget to update the `build.gradle`.

```
buildscript {
    repositories {
        mavenCentral()
    }
}

dependencies {
    implementation 'io.github.ShawnLin013:number-picker:2.4.13'
}
```
