### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by bluepixelservices** [ShawnLin013/NumberPicker#193]
Can you please add 1 feature :
 
1) stop recursive scrolling at end of last number  e.g. if I have 1 to 25 then at 25 scrolling should be stop and not scroll to again 1

**Comment by CreatorB** [comment]
I need it too

**Comment by ShawnLin013** [comment]
@bluepixelservices @CreatorB 
Use the following code
`numberPicker.setWrapSelectorWheel(false);`
or
`app:np_wrapSelectorWheel="false"`
