### ISSUE TITLE
Migrate to Maven from Jcenter

### ISSUE THREAD

**Issue by yianniscy84** [ShawnLin013/NumberPicker#194]
With the deprecation of JCenter can you move this to Maven. Thank you
https://developer.android.com/studio/build/jcenter-migration

**Comment by dhivya-purushothaman-appasamy** [comment]
Please I too need it

**Comment by ShawnLin013** [comment]
@yianniscy84 @dhivya-purushothaman-appasamy 
Successfully migrated to Maven Central Repository. Thanks!
Don't forget to update the `build.gradle`.

```
buildscript {
    repositories {
        mavenCentral()
    }
}

dependencies {
    implementation 'io.github.ShawnLin013:number-picker:2.4.13'
}
```

**Comment by dhivya-purushothaman-appasamy** [comment]
Thank you so much








---- On Sat, 22 May 2021 22:30:23 +0530 Shawn ***@***.***> wrote ----




https://github.com/yianniscy84 https://github.com/dhivya-purushothaman-appasamy
 Successfully migrated to Maven Central Repository. Thanks!
 Don't forget to update the build.gradle.
buildscript {
    repositories {
        mavenCentral()
    }
}

dependencies {
    implementation 'io.github.ShawnLin013:number-picker:2.4.13'
}
