### ISSUE TITLE
Cannot set divider thickness in java

### ISSUE THREAD

**Issue by lukaspili** [ShawnLin013/NumberPicker#20]
Hi,
As the title says, divider thickness can only be set in xml, because `mSelectionDividerThickness` is private.

Thanks.

**Comment by ShawnLin013** [comment]
Hi @lukaspili,
It's supported at v2.2.0.
`numberPicker.setDividerThickness(int thickness);`

**Comment by lukaspili** [comment]
Thank you @ShawnLin013
