### ISSUE TITLE
Initial value is blank when using formatter

### ISSUE THREAD

**Issue by kris-sum** [ShawnLin013/NumberPicker#22]
It seems like the initial value is blank when i'm using a formatter:
![with_formatter](https://cloud.githubusercontent.com/assets/2246940/20350336/730892e8-ac06-11e6-817e-17509ec4046d.png)

It functions fine, but the value only appears after I've spun the number picker.

When I don't specify a formatter, it works fine:
![without_formatter](https://cloud.githubusercontent.com/assets/2246940/20350338/74f494bc-ac06-11e6-97f1-a74a0dac4014.png)

The formatter I have is very simple - I just need increments of 5 instead of 1:
```
class StepFormatter implements com.shawnlin.numberpicker.NumberPicker.Formatter {
        @Override
        public String format(int value) {
                return "" + value*5;
                }
};
```

**Comment by ShawnLin013** [comment]
Hi @kris-sum,
Sorry for the late reply.
I was try to implement your formatter like ` numberPicker.setFormatter(new StepFormatter())`  in sample code. [http://imgur.com/bsQcaQu.png](http://imgur.com/bsQcaQu.png)
It's working fine. [http://imgur.com/OrzrK9S.png](http://imgur.com/OrzrK9S.png)
What version that you are using?

**Comment by kris-sum** [comment]
No worries @ShawnLin013 :)
I have the number wrapping turned off, and the initial value gets set to a non-zero value, could that be it?
My gradles is using "com.shawnlin:number-picker:2.1.0"

**Comment by ShawnLin013** [comment]
In this case, you should use `setDisplayedValues` instead of `setFormatter`.
```
int length = 10;
int level = 5;
String[] numbers = new String[length];
for (int i = 0; i < numbers.length; i++) {
    numbers[i] = String.valueOf((i + 1) * level);
}
numberPicker.setMinValue(1);
numberPicker.setMaxValue(length);
numberPicker.setDisplayedValues(numbers);
numberPicker.setValue(5);
```

**Comment by kris-sum** [comment]
Aye, i've switched to that, thanks.
