### ISSUE TITLE
Wrap Selector Wheel Setting Ignored

### ISSUE THREAD

**Issue by stephenmcbride** [ShawnLin013/NumberPicker#26]
When setting min/max values for the number picker, the global boolean for wrapping the selector wheel is overwritten by the following lines:
` boolean wrapSelectorWheel = mMaxValue - mMinValue > mSelectorIndices.length;
    setWrapSelectorWheel(wrapSelectorWheel); `

**Comment by ShawnLin013** [comment]
Please use `setWrapSelectorWheel` after `setMinValue` or `setMaxValue`.

**Comment by nevermore1488** [comment]
so the corresponding xml attribute is useless?
