### ISSUE TITLE
[Q] Why does your library require minsdk = 16?

### ISSUE THREAD

**Issue by hnvn** [ShawnLin013/NumberPicker#27]

**Comment by ShawnLin013** [comment]
This library is based on Android 4.0 NumberPicker.

**Comment by Hippoi** [comment]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.shawnlin:number-picker:2.3.0] C:\Users\alvar\.android\build-cache\6ed1b3c5c955e4c0bc5a88b40bfa7fe276cae97b\output\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="com.shawnlin.numberpicker" to force usage


Can you help me?

**Comment by ShawnLin013** [comment]
You can upgrade your minSdkVersion from 15 to 16 or add `<uses-sdk tools:overrideLibrary="com.shawnlin.numberpicker"/>` to your AndroidManifest.xml
