### ISSUE TITLE
Support horizontal mode?

### ISSUE THREAD

**Issue by webserveis** [ShawnLin013/NumberPicker#3]
I great, you component, is posible set view in horizontal mode¿?

**Comment by ShawnLin013** [comment]
Unfortunately, It' not supported yet :'(

**Comment by jgamedev** [comment]
+1 For this...  lots of custom pickers out there but I suppose most people looking for implementation are doing it because they need horizontal mode

**Comment by webserveis** [comment]
One day I saw a component, I no longer remember which, in the event onDraw is where rotating the view, I'm sorry my programming skills are not enough to provide more.

**Comment by jgamedev** [comment]
Lol, neither are mine!  :smile: 
Thanks for sharing your component with the community.
Open source developers like the best ;-)

**Comment by ShawnLin013** [comment]
Dear @webserveis  and @jgamedev ,

Thank you for your recommendation.  :heart: 
Horizontal mode is supported now!

```
<com.shawnlin.numberpicker.NumberPicker
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:np_orientation=horizontal />
```
