### ISSUE TITLE
ANR when wrap=false and wheelItemCount is set to >= 6

### ISSUE THREAD

**Issue by PieterAelse** [ShawnLin013/NumberPicker#37]
Steps to reproduce:
- Checkout the sample
- Open the layout file
- Edit `number_picker` and set:
```
app:np_wheelItemCount="7"
app:np_wrapSelectorWheel="false"
```
- Scroll to the bottom of the numberpicker, ANR will happen
- ANR also happens when scrolling down and going back to top of numberpicker again

I wasn't able to get ANR with the value of 6 or lower.

**Comment by ShawnLin013** [comment]
Set the text size smaller should fix this issue.

**Comment by ShawnLin013** [comment]
Fixed at v2.4.2
