### ISSUE TITLE
Scrolling is 'tripping' when at top or bottom when no-wrap and itemCount is >= 5

### ISSUE THREAD

**Issue by PieterAelse** [ShawnLin013/NumberPicker#38]
Steps to reproduce:
- Checkout the sample
- Open the layout file
- Edit `number_picker` and set:
```
app:np_wheelItemCount="5"
app:np_wrapSelectorWheel="false"
```
- Scroll to the top or bottom of the numberpicker
- Try to normally (/slowly) get to the previous/next number, scrolling will 'trip'

Only way to escape the top/bottom position is with a fast fling.

See video for demo: 
[NumberPicker_NoWrap_ItemCount5_tripping.zip](https://github.com/ShawnLin013/NumberPicker/files/750037/NumberPicker_NoWrap_ItemCount5_tripping.zip)

**Comment by ShawnLin013** [comment]
Fixed at v2.4.2

**Comment by crackTheCode** [comment]
@ShawnLin013 problem present in 2.4.10 android 10 oneplus 6 device. Any ideas?

**Comment by bd901029** [comment]
I think I have same issue. I want to fire the onValueChangedListener when scroll is finished. So I set onScrollStateListener and checked the scrollState is Idle. But it doesn't fire when I scroll small range 1 or 2. I need answer asap

**Comment by ShawnLin013** [comment]
This issue has been fixed at v2.4.11. @crackTheCode @bd901029
