### ISSUE TITLE
Failed to find style 'numberPickerStyle' in current theme

### ISSUE THREAD

**Issue by percula** [ShawnLin013/NumberPicker#42]
I keep getting this error in Android Studio when previewing the layout. Do I need to declare a style in my theme for the numberPickerStyle attribute? The sample app does not appear to have anything like that. Thanks!

`Failed to find style 'numberPickerStyle' in current theme`

**Comment by ShawnLin013** [comment]
Fixed at v2.4.2

**Comment by percula** [comment]
Nice, thanks! Great library you have made =)
