### ISSUE TITLE
using app:np_height scales text size

### ISSUE THREAD

**Issue by polaroidkidd** [ShawnLin013/NumberPicker#47]
Love the layout and everything, but unfortunately the text size scales with the np_height/width dimension. Here is how I tried to implement it. 

```
    <com.shawnlin.numberpicker.NumberPicker
        
        app:np_height="30dp"
        app:np_textSize="20sp"
        
        android:id="@+id/snooze_duration_picker"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:np_dividerColor="@color/colorSleepArc"
        app:np_max="60"
        app:np_min="0"
        app:np_textColor="@color/colorAccent"
        app:np_orientation="horizontal"
        app:np_value="5"
        android:layout_toEndOf="@+id/snooze_button"
        app:np_typeface="sans-serif-thin"
        />
```

**Comment by ShawnLin013** [comment]
Text size doesn't scale the layout dimension.
The layout is scaled by ` app:np_height="30dp"`.  😈

**Comment by polaroidkidd** [comment]
Apologies. What I meant was that when I set text size as 5sp and np_height as 50dp, the text stretches in height. How would I get the text to remain 5sp while I increase the bar-height?

**Comment by ShawnLin013** [comment]
Scale the layout dimension does not increase the text size too.
Did you set the text size programmatically?

**Comment by rdebbiny** [comment]
Hi, I'm also seeing the same behavior.
Changing either: `app:np_height"` or `app:np_width` will distort the font.. my picker is being used horizontally.  

`<com.shawnlin.numberpicker.NumberPicker
		android:id="@+id/program_number_picker"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_centerInParent="true"
		android:layout_alignParentBottom="true"
		android:layout_marginBottom="49dp"
		app:np_width="156dp"
		app:np_height="49dp"
		app:np_dividerColor="@color/blue"
		app:np_dividerDistance="40dp"
		app:np_min="1"
		app:np_max="16"
		app:np_wheelItemCount="5"
		app:np_wrapSelectorWheel="true"
		app:np_textColor="@color/grey"
		app:np_selectedTextColor="@color/light_grey"
		app:np_textSize="34sp"
		app:np_orientation="horizontal"
		app:np_value="3"/>`
