### ISSUE TITLE
Selection of Numbers

### ISSUE THREAD

**Issue by polaroidkidd** [ShawnLin013/NumberPicker#48]
I was wondering if it was somehow possible to disable the selection on the first touch so the user can only scroll through the different numbers? 

![selection_setting](https://cloud.githubusercontent.com/assets/11783457/24107909/5c9b076a-0d8c-11e7-8c3d-384a8b254e39.gif)

**Comment by ShawnLin013** [comment]
I am not sure your issue.
The default selected index of numbers is zero.
More detail?

**Comment by polaroidkidd** [comment]
when I try to scroll through numbers (0-100), starting at 0, with the first scroll I make it to say, 48, then I want to scroll again from lef to right, but my second touch on one of the golden bars sets the number back to something closer to 0. Am I making sense? It's kinda heard to explain..

**Comment by ShawnLin013** [comment]
So you want to picker auto reset back to 0 after scroll?

**Comment by polaroidkidd** [comment]
I want to be able to scroll through the numbers (center selects the current number) and disable setting numbers by touching one of the bars.

**Comment by ShawnLin013** [comment]
It's ok. 😆
