### ISSUE TITLE
setMaxValue() resets wrapSelectorWheel value

### ISSUE THREAD

**Issue by sp0rk** [ShawnLin013/NumberPicker#55]
I'm not sure if this is the intended behaviour. If it is, just close the issue.

**Comment by ShawnLin013** [comment]
`setMaxValue()` and `setMinValue()` both reset the wrapSelectorWheel.

If you want to setWrapSelectorWheel programmatically,
you should call `setWrapSelectorWheel` after `setMinValue` and `setMaxValue`.
```
numberPicker.setMinValue(min);
numberPicker.setMaxValue(max);
numberPicker.setWrapSelectorWheel(false);
```

**Comment by aitbaali** [comment]
@ShawnLin013 thanks for this great library.

I have the issue and your solution not working for me, but when I modify `setWrapSelectorWheel(boolean wrapSelectorWheel)`  like

`public void setWrapSelectorWheel(boolean wrapSelectorWheel) {
        final boolean wrappingAllowed = (mMaxValue - mMinValue) >= mSelectorIndices.length;
        if ((!wrapSelectorWheel || wrappingAllowed) && wrapSelectorWheel != mWrapSelectorWheel) {
            mWrapSelectorWheel = wrapSelectorWheel;
            initializeSelectorWheelIndices();
            updateInputTextView();
            tryComputeMaxWidth();
            invalidate();
        }
    }`

it works great. I have done a little copy/past, maybe you have to reset the layout after wrapSelectorWheel changed.

**Comment by ShawnLin013** [comment]
@absimas You got it. `Invalidate()` in `setWrapSelectorWheel()` is better than `setMaxValue() `and `setMinValue()`. Thank you for your suggestion.
