### ISSUE TITLE
Change height/width

### ISSUE THREAD

**Issue by vados60** [ShawnLin013/NumberPicker#57]
Hello!

Is there any chance to set number of currently visible rows except selected one?
Or is there any chance to hide all other rows except selected?

if I set 
app:np_wheelItemCount="1"

when try to scroll the app crashes with IndexOutOfBounds exception
java.lang.ArrayIndexOutOfBoundsException: length=1; index=-1
                                                               at com.shawnlin.numberpicker.NumberPicker.incrementSelectorIndices(NumberPicker.java:1695)

WBR
Vadim

**Comment by scastro** [comment]
I have the same issue.

Also, the control uses the space above and below as if would have more items to show.

**Comment by ShawnLin013** [comment]
Hi @vados60, 
Have you tried setting the text color to transparent?
`numberPicker.setTextColorResource(android.R.color.transparent);`
or
` app:np_textColor="@android:color/transparent"`

And no need to set the wheel item count to 1.

**Comment by sdugaoxiang** [comment]
I met the same issue, and I think it is a bug. 
I have checked the code. When app:np_wheelItemCount is set as 1, the size of selectorIndices will be 0, then the IndexOutOfBound will happen in line 1775.

**Comment by duetdroid** [comment]
I met the same issue, and I think it is a bug.
I have checked the code. When app:np_wheelItemCount is set as 1, the size of selectorIndices will be 0(line 2113), then the IndexOutOfBound will happen in line 1775.

**Comment by soshial** [comment]
I also have the same bug. A temporary kludge proposed by @ShawnLin013 works.

**Comment by ShawnLin013** [comment]
Supported at v2.4.6
