### ISSUE TITLE
It's not getting the selected value?

### ISSUE THREAD

**Issue by AlaaZarifa** [ShawnLin013/NumberPicker#58]
There are a bunch of pickers in a dialog, I want the selected value to be stored in an int value so that I can use for other stuff..! but it's not seem to be working with me..!?

I've tried this 
```
PicValue_1 = numberPicker1.getValue();
Log.i("PicValue_1 TEST_1", "" + numberPicker1.getValue());
```

the log never showed..!

then I've tried this.

    numberPicker1.setOnValueChangedListener(new OnValueChangeListener() {
      @Override
      public void onValueChange(NumberPicker picker, int oldVal, int newVal) {

        PicValue_1 = newVal;
        Log.i("PicValue_1 TEST_2", "" + numberPicker1.getValue());

        Toast.makeText(MainActivity.this, "picker changed from  " + numberPicker1.getValue() + "|" + oldVal + " to " + newVal  , Toast.LENGTH_SHORT).show();

      }
    });

..But the log never showed again neither the toast..!? I tried to move the listener inside the dialog button event listener, but no luck..? what I'm doing wrong..!

**Comment by ShawnLin013** [comment]
Have you tried checking whether the NumberPicker is null?

```
Log.e("MainActivity", "getValue: " + numberPicker.getValue());
```
or
```
numberPicker.setOnValueChangedListener(new NumberPicker.OnValueChangeListener() {
    @Override
    public void onValueChange(NumberPicker picker, int oldVal, int newVal) {
        Log.e("MainActivity", "newVal: " + newVal);
    }
});
```

**Comment by AlaaZarifa** [comment]
the log wasn't showing at all..!
But after some digging, it turns out the problem was relating to binding wrong views and it got nothing to do with your library.!

I'm sorry for that..!
And thanks for this awesome library, I think google should replace their NumPicker widget with yours since it's way much better..!
