### ISSUE TITLE
np_orientation cannot be set

### ISSUE THREAD

**Issue by usergoodvery** [ShawnLin013/NumberPicker#59]
Hi

I don't seem to be able to set the orientation to vertical; I tried both modes, xml and java but the picker always render in horizontal.

Android 7.1.1 api25

**Comment by ShawnLin013** [comment]
Have you tried the sample app?
Default orientation should be vertical.

```
<com.shawnlin.numberpicker.NumberPicker
    android:id="@+id/number_picker"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content" />
```

**Comment by usergoodvery** [comment]
Hi,
I tried as per the sample code. I also tried to set it explicitly, but neither worked.

**Comment by ShawnLin013** [comment]
I tried installing the sample app on Android 7.1.1 emulator.
And it's working correctly.
Any more details or your code?

**Comment by usergoodvery** [comment]
Hi,
I am not doing anything special really. My layout code is below, where I set the orientation explicitly.
I have not run the sample app.

I also tried to set orientation programatically:
 numberPicker.setOrientation(NumberPicker.VERTICAL);

<com.shawnlin.numberpicker.NumberPicker
                        android:id="@+id/number_picker"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_alignParentRight="true"
                        android:layout_marginRight="16dp"
                        android:layout_marginEnd="16dp"
                        app:np_textSize="12sp"
                        app:np_dividerColor="#EEDDDD"
                        app:np_max="200"
                        app:np_min="0"
                        app:np_selectedTextColor="?attr/colorPrimaryDark"
                        app:np_orientation="vertical"
                        app:np_value="0" />

**Comment by Shaw6157** [comment]
Hi Shawn,
When I tried to set programmatically, got some error:
Must be one of: LinearLayout.HORIZONTAL, LinearLayout.VERTICAL less... (Ctrl+F1) 
Must be one of: NumberPicker.VERTICAL, NumberPicker.HORIZONTAL less... (Ctrl+F1) 

I didn't check your codes, but I saw that NumberPicker.VERTICAL is equal to LinearLayout.HORIZONTAL.
If I used either of this, IDE warned me the other error message, but anyway I could deploy it and run it correctly.

**Comment by ShawnLin013** [comment]
Close this inactive issue for now. Please reopen this issue if are still encountering problems.
