### ISSUE TITLE
Items order

### ISSUE THREAD

**Issue by andrey-kaiser** [ShawnLin013/NumberPicker#60]
First of all, thank you for an awesome library!
It would be cool to add possibility to change an order of numbers to opposite, especially useful for vertical orientation in my case.

**Comment by ShawnLin013** [comment]
Have you tried installing sample app?

**Comment by ShawnLin013** [comment]
Added at v2.4.4.

` numberPicker.setOrder(NumberPicker.DESCENDING);`
or
`app:np_order="descending"`
