### ISSUE TITLE
Android crash when using the library

### ISSUE THREAD

**Issue by bendaf** [ShawnLin013/NumberPicker#7]
Interesting, that since I have included the library to my project I have experiencing this crash: 
http://stackoverflow.com/questions/36447078/setselection-on-a-spinner-crashes-when-layout-weight-is-assigned-to-spinner/38790474#38790474

If I remove the library the crash disappears. 

I have found a workaround and don't understand the coherency but I am preatty sure in this issue so I wanted to share. I have posted my workaround to the stackoverflow post.

**Comment by ShawnLin013** [comment]
Close this inactive issue for now. Please reopen this issue if are still encountering problems.
