### ISSUE TITLE
value picker be changed in previous fragment when click back from after fragment

### ISSUE THREAD

**Issue by truong081294** [ShawnLin013/NumberPicker#74]
p/s: In MVVM

**Comment by TejaDroid** [comment]
I am also getting the same issue while come back to previous fragment...

@truong081294 , Have you got a solution?

**Comment by ShawnLin013** [comment]
Have you tried using `setValue()` in `onResume()`?

**Comment by ShawnLin013** [comment]
Close this inactive issue for now. Please reopen this issue if are still encountering problems.
