### ISSUE TITLE
How can i set value like 40 45 50 55 60 65 etc...

### ISSUE THREAD

**Issue by kushanshah11** [ShawnLin013/NumberPicker#77]
Hi @ShawnLin013 ,

how can i set value in difference of 5 and yes i want to start it from 40 not from 0 or 5 .

i have checked solutions for same 

 int length = 50;
            int level = 5;
            String[] numbers = new String[length];
            for (int i = 0; i < numbers.length; i++) {
                numbers[i] = String.valueOf((i + 1) * level);
            }
            numberPicker.setMinValue(40);
            numberPicker.setMaxValue(length);
            numberPicker.setDisplayedValues(numbers);
            numberPicker.setValue(5);

but it will start from 5 to 55 i want menu from 40 45 to 100 ..

thanks in advance

**Comment by ShawnLin013** [comment]
@kushanshah11 
Please try the following example
```
int level = 5;
int max = 100;
int min = 40;
int length = (max - min) / level + 1;
String[] numbers = new String[length];
for (int i = 0; i < numbers.length; i++) {
    numbers[i] = String.valueOf(min + i * level);
}
numberPicker.setMinValue(1);
numberPicker.setMaxValue(length);
numberPicker.setDisplayedValues(numbers);
numberPicker.setValue(0);
```
