### ISSUE TITLE
SelectedText not show center when increase size?

### ISSUE THREAD

**Issue by tuanbaros** [ShawnLin013/NumberPicker#78]
When I increase size of SelectedText, it not show center of number picker, how can fix ??? (My English not good, sorry).

**Comment by ShawnLin013** [comment]
Ref to #72

**Comment by BichThien** [comment]
Hi @ShawnLin013, i try to set itemCount = 1 but not work, then im trying to make sense by setColorText = transparent and add itemSpace. Hence, i got the same issue when increase textSize. I see comment that it issue was fixed? Pls give me more infor about this. Thank u very much.
