### ISSUE TITLE
Two Lines String

### ISSUE THREAD

**Issue by mmd44** [ShawnLin013/NumberPicker#79]
I need 2 lines for each item in the picker (\n is not interpreted well).

**Comment by ShawnLin013** [comment]
Hi @mmd44 and @esrabindra,

Thank you for your suggestion. 🙏 

This feature is supported at v2.4.7. Please try the following code snippet.

```java
String[] data = {"A\nA", "B", "C", "D", "E", "F", "G", "H", "I"};
numberPicker.setMinValue(1);
numberPicker.setMaxValue(data.length);
numberPicker.setDisplayedValues(data);
```

**Comment by esrabindra** [comment]
It works perfectly.
