### ISSUE TITLE
Add support for negative values

### ISSUE THREAD

**Issue by webserveis** [ShawnLin013/NumberPicker#8]
<com.shawnlin.numberpicker.NumberPicker
        android:id="@+id/number_picker"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        app:np_width="64"
        app:np_height="180"
        app:np_dividerColor="@color/colorPrimary"
        app:np_formatter="%02d"
        app:np_max="7"
        app:np_min="-7"
        app:np_textColor="@color/colorPrimary"
        app:np_textSize="30sp"
        app:np_typeface="sans-serif-light" />

Caused by: java.lang.IllegalArgumentException: minValue must be >= 0

**Comment by ShawnLin013** [comment]
Fixed at #11.
