### ISSUE TITLE
SetDisplayedValues problem

### ISSUE THREAD

**Issue by ynpl** [ShawnLin013/NumberPicker#81]
English is not very good, please forgive me
If I customize DisplayedValues, set setMinValue will fail, he is the first Item or a, but the last item will change

     starTime.add("a");
        starTime.add("b");
        starTime.add("c");
        starTime.add("d");
        starTime.add("e");
        starTime.add("f");
        starTime.add("g");
        starTime.add("h");
        starTime.add("o");
        starTime.add("j");
        starTime.add("k");
        String[] starArm = (String[]) starTime.toArray(new String[starTime.size()]);
        profileOffcalendarTimeNp = (NumberPicker) findViewById(R.id.profile_offcalendar_time_np);
        profileOffcalendarTimeNp.setDisplayedValues(starArm);
        profileOffcalendarTimeNp.setMinValue(6);
        profileOffcalendarTimeNp.setMaxValue(starTime.size());
        profileOffcalendarTimeNp.setValue(7);
        profileOffcalendarTimeNp.setWrapSelectorWheel(false);
This is the time to show it:
abcdefg 
Why not?
fghojk

**Comment by ShawnLin013** [comment]
主要有兩個部份需要做修改
1. 將 setMinValue 設定成 1
2. 將 setDisplayedValues 移動到 setMinValue 和 setMaxValue 的後面

```
String[] data = {"A", "B", "C", "D", "E", "F", "G", "H", "I"};
numberPicker.setMinValue(1);
numberPicker.setMaxValue(data.length);
numberPicker.setDisplayedValues(data);
numberPicker.setValue(7);
numberPicker.setWrapSelectorWheel(false);
```
