### ISSUE TITLE
Error after adding dependency!

### ISSUE THREAD

**Issue by Pawnr** [ShawnLin013/NumberPicker#92]
After i add the dependency at build.gradle and sync, i get those errors?
http://tinypic.com/r/2w1txnd/9
http://i66.tinypic.com/2nhdtfo.png

**Comment by Pawnr** [comment]
Its not working again. I first add the dependency and after i sync i get the error:
"http://i63.tinypic.com/qpp6z6.png"
After i add the google maven repository and sync the project again, i get the above errors, i tried cleaning/rebuilding but nothing, same above errors.

**Comment by Pawnr** [comment]
Any answers @ShawnLin013 ?

**Comment by ShawnLin013** [comment]
Sorry, I cannot reproduce this issue.
Have you tried using older version like 2.4.4.?

**Comment by Pawnr** [comment]
Version 2.4.4 is working, i added it, and got no errors. Can i know the differences between 2.4.4-5?

**Comment by ShawnLin013** [comment]
Sure! Ref to https://github.com/ShawnLin013/NumberPicker/releases/tag/v2.4.5

**Comment by Pawnr** [comment]
Is there a way in version 2.4.4 to remove this fadingEdge, i really need to remove it?

**Comment by ShawnLin013** [comment]
Close this inactive issue for now. Please reopen this issue if are still encountering problems.
